const gallerykumarkom = [
  {
    category: "All",
    images: [
      
      "/gallery/kumarkom_gallery/life_style/Exterior-7.jpg",
      "/gallery/kumarkom_gallery/life_style/Exterior-6.jpg",
      "/gallery/kumarkom_gallery/life_style/Games.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle__speciality-restaurant-J-2.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bar-J-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bicycle-J-4.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bicycle-J-6.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Boating-J-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bridal-Boating-J-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-bridge-19-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-fishing-7-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-fishing-12-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-game-room-J-2.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-houseboat-D-9-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-houseboat-J-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-houseboat-J-7.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-kathakali-J-5.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-outdoor-dinning-J-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Pool-J-2.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Pottery-J-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Restaurant-J-8.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Restaurant-J-10.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-8.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-17.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-22.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-27.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-37.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-yoga-A-13-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-yoga-C-13-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Pool-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Pool-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Pool-5.jpg",
      "/gallery/kumarkom_gallery/life_style/Spa.jpg",

      "/gallery/kumarkom_gallery/event_and_wedding/Banquet-1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/banquet-social.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Board-room.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Lifestyle-Bridal-Boating-J-1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Lifestyle-Bridal-closeup-J-10.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-2.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-3.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-4.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-5.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-6.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-7.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-8.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-9.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-10.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-11.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-12.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/zuri-sataaward1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/zuri-sataaward2.jpg",

      "/gallery/kumarkom_gallery/maya_spa/Lifestyle-Kerala-spa-J-1.jpg",
      "/gallery/kumarkom_gallery/maya_spa/Lifestyle-Kerala-spa-J-5.jpg",
      "/gallery/kumarkom_gallery/maya_spa/Spa-Kerala-Therapy.jpg",
      "/gallery/kumarkom_gallery/maya_spa/Spa-Western-Therapy.jpg",

      "/gallery/kumarkom_gallery/dining/Bar-1.jpg",
      "/gallery/kumarkom_gallery/dining/dining.jpg",
      "/gallery/kumarkom_gallery/dining/Food-1__13-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-1__21-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-2__1-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-2__26-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-3__7-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-3__15-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-4__14-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-8__15-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-9__5-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-11__6.jpg",
      "/gallery/kumarkom_gallery/dining/Food-12__7-1.jpg",
      "/gallery/kumarkom_gallery/dining/Restaurant-2.jpg",
      "/gallery/kumarkom_gallery/dining/Restaurant-3.jpg",
      "/gallery/kumarkom_gallery/dining/Restaurant-4.jpg",
      "/gallery/kumarkom_gallery/dining/Speciality-Restaurant.jpg",

      "/gallery/kumarkom_gallery/room_and_suites/Lifestyle-Room-J-4.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-1-view-A__flower-2.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-cottage-2.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-Cottage-Balcony-1.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-Villa-Bathroom.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-villa-bedroom-1.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-villa-living.jpg",
    ],
  },
  {
    category: "Room & Suites",
    images: [
      "/gallery/kumarkom_gallery/room_and_suites/Lifestyle-Room-J-4.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-1-view-A__flower-2.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-cottage-2.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-Cottage-Balcony-1.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-Villa-Bathroom.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-villa-bedroom-1.jpg",
      "/gallery/kumarkom_gallery/room_and_suites/Room-villa-living.jpg",
    ],
  },
  {
    category: "Dining",
    images: [
      "/gallery/kumarkom_gallery/dining/Bar-1.jpg",
      "/gallery/kumarkom_gallery/dining/dining.jpg",
      "/gallery/kumarkom_gallery/dining/Food-1__13-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-1__21-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-2__1-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-2__26-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-3__7-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-3__15-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-4__14-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-8__15-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-9__5-1.jpg",
      "/gallery/kumarkom_gallery/dining/Food-11__6.jpg",
      "/gallery/kumarkom_gallery/dining/Food-12__7-1.jpg",
      "/gallery/kumarkom_gallery/dining/Restaurant-2.jpg",
      "/gallery/kumarkom_gallery/dining/Restaurant-3.jpg",
      "/gallery/kumarkom_gallery/dining/Restaurant-4.jpg",
      "/gallery/kumarkom_gallery/dining/Speciality-Restaurant.jpg",
    ],
  },
  {
    category: "Maya spa",
    images: [
      "/gallery/kumarkom_gallery/maya_spa/Lifestyle-Kerala-spa-J-1.jpg",
      "/gallery/kumarkom_gallery/maya_spa/Lifestyle-Kerala-spa-J-5.jpg",
      "/gallery/kumarkom_gallery/maya_spa/Spa-Kerala-Therapy.jpg",
      "/gallery/kumarkom_gallery/maya_spa/Spa-Western-Therapy.jpg",
    ],
  },
  {
    category: "Event and Wedding",
    images: [
      "/gallery/kumarkom_gallery/event_and_wedding/Banquet-1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/banquet-social.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Board-room.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Lifestyle-Bridal-Boating-J-1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Lifestyle-Bridal-closeup-J-10.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-2.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-3.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-4.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-5.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-6.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-7.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-8.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-9.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-10.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-11.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/Wedding-12.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/zuri-sataaward1.jpg",
      "/gallery/kumarkom_gallery/event_and_wedding/zuri-sataaward2.jpg",
    ],
  },
  {
    category: "Lifestyle",
    images: [
      "/gallery/kumarkom_gallery/life_style/Exterior-6.jpg",
      "/gallery/kumarkom_gallery/life_style/Exterior-7.jpg",
      "/gallery/kumarkom_gallery/life_style/Games.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle__speciality-restaurant-J-2.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bar-J-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bicycle-J-4.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bicycle-J-6.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Boating-J-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Bridal-Boating-J-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-bridge-19-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-fishing-7-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-fishing-12-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-game-room-J-2.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-houseboat-D-9-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-houseboat-J-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-houseboat-J-7.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-kathakali-J-5.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-outdoor-dinning-J-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Pool-J-2.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Pottery-J-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Restaurant-J-8.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Restaurant-J-10.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-8.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-17.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-22.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-27.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-Room-J-37.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-yoga-A-13-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Lifestyle-yoga-C-13-copy.jpg",
      "/gallery/kumarkom_gallery/life_style/Pool-1.jpg",
      "/gallery/kumarkom_gallery/life_style/Pool-3.jpg",
      "/gallery/kumarkom_gallery/life_style/Pool-5.jpg",
      "/gallery/kumarkom_gallery/life_style/Spa.jpg",
    ],
  },
];

export default gallerykumarkom;
